# =============================================================================
# utils/language.py  —  Multi-Language Support: English · Hindi · Telugu
# =============================================================================

TRANSLATIONS = {
    "English": {
        "app_name":"Smart Crop Recommendation","nav_home":"Home",
        "nav_predict":"Predict Crop","nav_dashboard":"Analytics Dashboard",
        "nav_performance":"Model Performance","nav_login":"Login","nav_logout":"Logout",
        "select_lang":"Select Language",
        "home_hero_title":"Smart Crop Rotation\nRecommendation System",
        "home_hero_subtitle":"AI-Powered Agriculture Decision Support",
        "home_hero_desc":"Make data-driven farming decisions using soil nutrients, climate data, and crop rotation history. Powered by a Random Forest model with 94%+ accuracy.",
        "home_get_started":"Get Started →","home_view_analytics":"View Analytics",
        "home_features_title":"Why Choose This System?",
        "home_feat1_title":"AI-Powered Predictions","home_feat1_desc":"Random Forest trained on 2,200 real samples.",
        "home_feat2_title":"Fertilizer Guidance","home_feat2_desc":"Tailored fertilizer suggestions for every crop.",
        "home_feat3_title":"Crop Rotation Support","home_feat3_desc":"Smart notes to protect long-term soil health.",
        "home_feat4_title":"Multi-Language","home_feat4_desc":"English, Hindi, and Telugu support.",
        "home_feat5_title":"Rich Analytics","home_feat5_desc":"Interactive charts: distribution, nutrients, rainfall.",
        "home_feat6_title":"Model Transparency","home_feat6_desc":"Confusion matrix, feature importance, per-class metrics.",
        "home_stats_crops":"Crops Supported","home_stats_samples":"Training Samples",
        "home_stats_accuracy":"Model Accuracy","home_stats_langs":"Languages",
        "login_title":"Welcome Back","login_subtitle":"Sign in to access your crop dashboard",
        "login_username":"Username","login_password":"Password","login_btn":"Sign In",
        "login_no_account":"Don't have an account?","login_register":"Register here",
        "login_error":"Invalid username or password.","login_demo":"Demo: admin / admin123",
        "pred_title":"Crop Prediction","pred_subtitle":"Enter your farm details to receive the best crop recommendation.",
        "pred_soil":"Soil Nutrients","pred_climate":"Climate Conditions","pred_rotation":"Previous Crop",
        "label_N":"Nitrogen (N)","label_P":"Phosphorus (P)","label_K":"Potassium (K)",
        "label_temp":"Temperature (°C)","label_humidity":"Humidity (%)","label_ph":"Soil pH",
        "label_rainfall":"Rainfall (mm)","label_prev":"Previous Crop",
        "predict_btn":"Predict Crop","reset_btn":"Reset Form",
        "result_title":"Recommended Crop","result_confidence":"Confidence",
        "result_fertilizer":"Fertilizer Suggestion","result_rotation":"Rotation Note","result_top5":"Top 5 Probabilities",
        "dash_title":"Analytics Dashboard","dash_subtitle":"Visual insights from 2,200 crop samples",
        "chart_dist":"Crop Distribution","chart_nutrients":"Avg. Soil Nutrients by Crop",
        "chart_rainfall":"Rainfall vs Crop","chart_ph":"Soil pH by Crop",
        "chart_corr":"Feature Correlation","chart_prev":"Previous Crop Frequency",
        "perf_title":"Model Performance","perf_subtitle":"Random Forest — trained on 1,760 samples, tested on 440",
        "metric_accuracy":"Accuracy","metric_precision":"Precision","metric_recall":"Recall","metric_f1":"F1 Score",
        "chart_confusion":"Confusion Matrix","chart_importance":"Feature Importance","perf_class_metrics":"Per-Class Metrics",
        "footer_copy":"© 2025 Smart Crop Recommendation System. Built for Sustainable Agriculture.",
    },
    "Hindi": {
        "app_name":"स्मार्ट फसल अनुशंसा","nav_home":"मुख्य पृष्ठ",
        "nav_predict":"फसल की भविष्यवाणी करें","nav_dashboard":"विश्लेषण डैशबोर्ड",
        "nav_performance":"मॉडल प्रदर्शन","nav_login":"लॉगिन","nav_logout":"लॉगआउट",
        "select_lang":"भाषा चुनें",
        "home_hero_title":"स्मार्ट फसल चक्र\nअनुशंसा प्रणाली",
        "home_hero_subtitle":"AI-आधारित कृषि निर्णय सहायता",
        "home_hero_desc":"मिट्टी पोषक तत्वों, जलवायु डेटा और फसल चक्र इतिहास का उपयोग करके डेटा-आधारित कृषि निर्णय लें। 94%+ सटीकता वाले मॉडल द्वारा संचालित।",
        "home_get_started":"शुरू करें →","home_view_analytics":"विश्लेषण देखें",
        "home_features_title":"इस प्रणाली को क्यों चुनें?",
        "home_feat1_title":"AI-संचालित भविष्यवाणियाँ","home_feat1_desc":"2,200 वास्तविक नमूनों पर प्रशिक्षित मॉडल।",
        "home_feat2_title":"उर्वरक मार्गदर्शन","home_feat2_desc":"हर फसल के लिए अनुकूलित उर्वरक सुझाव।",
        "home_feat3_title":"फसल चक्र समर्थन","home_feat3_desc":"दीर्घकालिक मिट्टी स्वास्थ्य के लिए स्मार्ट नोट्स।",
        "home_feat4_title":"बहु-भाषा","home_feat4_desc":"अंग्रेजी, हिंदी और तेलुगु समर्थन।",
        "home_feat5_title":"समृद्ध विश्लेषण","home_feat5_desc":"इंटरैक्टिव चार्ट: वितरण, पोषक तत्व, वर्षा।",
        "home_feat6_title":"मॉडल पारदर्शिता","home_feat6_desc":"भ्रम मैट्रिक्स, फीचर महत्व, प्रति-वर्ग मेट्रिक्स।",
        "home_stats_crops":"समर्थित फसलें","home_stats_samples":"प्रशिक्षण नमूने",
        "home_stats_accuracy":"मॉडल सटीकता","home_stats_langs":"भाषाएँ",
        "login_title":"वापस स्वागत है","login_subtitle":"अपने डैशबोर्ड तक पहुँचने के लिए साइन इन करें",
        "login_username":"उपयोगकर्ता नाम","login_password":"पासवर्ड","login_btn":"साइन इन करें",
        "login_no_account":"खाता नहीं है?","login_register":"यहाँ पंजीकरण करें",
        "login_error":"अमान्य उपयोगकर्ता नाम या पासवर्ड।","login_demo":"डेमो: admin / admin123",
        "pred_title":"फसल भविष्यवाणी","pred_subtitle":"सर्वोत्तम फसल अनुशंसा पाने के लिए खेत का विवरण दर्ज करें।",
        "pred_soil":"मिट्टी पोषक तत्व","pred_climate":"जलवायु परिस्थितियाँ","pred_rotation":"पिछली फसल",
        "label_N":"नाइट्रोजन (N)","label_P":"फास्फोरस (P)","label_K":"पोटेशियम (K)",
        "label_temp":"तापमान (°C)","label_humidity":"आर्द्रता (%)","label_ph":"मिट्टी pH",
        "label_rainfall":"वर्षा (मिमी)","label_prev":"पिछली फसल",
        "predict_btn":"फसल की भविष्यवाणी करें","reset_btn":"फॉर्म रीसेट करें",
        "result_title":"अनुशंसित फसल","result_confidence":"विश्वास",
        "result_fertilizer":"उर्वरक सुझाव","result_rotation":"फसल चक्र नोट","result_top5":"शीर्ष 5 संभावनाएँ",
        "dash_title":"विश्लेषण डैशबोर्ड","dash_subtitle":"2,200 फसल नमूनों से दृश्य अंतर्दृष्टि",
        "chart_dist":"फसल वितरण","chart_nutrients":"औसत मिट्टी पोषक तत्व",
        "chart_rainfall":"वर्षा बनाम फसल","chart_ph":"फसल द्वारा pH",
        "chart_corr":"फीचर सहसंबंध","chart_prev":"पिछली फसल आवृत्ति",
        "perf_title":"मॉडल प्रदर्शन","perf_subtitle":"रैंडम फॉरेस्ट — 1,760 नमूनों पर प्रशिक्षित",
        "metric_accuracy":"सटीकता","metric_precision":"परिशुद्धता","metric_recall":"रिकॉल","metric_f1":"F1 स्कोर",
        "chart_confusion":"कन्फ्यूजन मैट्रिक्स","chart_importance":"फीचर महत्व","perf_class_metrics":"प्रति-वर्ग मेट्रिक्स",
        "footer_copy":"© 2025 स्मार्ट फसल अनुशंसा प्रणाली। टिकाऊ कृषि के लिए निर्मित।",
    },
    "Telugu": {
        "app_name":"స్మార్ట్ పంట సిఫారసు","nav_home":"హోమ్",
        "nav_predict":"పంట అంచనా వేయండి","nav_dashboard":"విశ్లేషణ డాష్‌బోర్డ్",
        "nav_performance":"మోడల్ పనితీరు","nav_login":"లాగిన్","nav_logout":"లాగ్అవుట్",
        "select_lang":"భాష ఎంచుకోండి",
        "home_hero_title":"స్మార్ట్ పంట మార్పిడి\nసిఫారసు వ్యవస్థ",
        "home_hero_subtitle":"AI-ఆధారిత వ్యవసాయ నిర్ణయ మద్దతు",
        "home_hero_desc":"నేల పోషకాలు, వాతావరణ డేటా మరియు పంట మార్పిడి చరిత్రను ఉపయోగించి డేటా-ఆధారిత నిర్ణయాలు తీసుకోండి. 94%+ ఖచ్చితత్వంతో నడపబడుతుంది.",
        "home_get_started":"ప్రారంభించండి →","home_view_analytics":"విశ్లేషణలు చూడండి",
        "home_features_title":"ఈ వ్యవస్థను ఎందుకు ఎంచుకోవాలి?",
        "home_feat1_title":"AI-ఆధారిత అంచనాలు","home_feat1_desc":"2,200 నిజమైన నమూనాలపై శిక్షణ పొందిన మోడల్.",
        "home_feat2_title":"ఎరువుల మార్గదర్శకత్వం","home_feat2_desc":"ప్రతి పంటకు అనుకూలమైన ఎరువుల సూచనలు.",
        "home_feat3_title":"పంట మార్పిడి మద్దతు","home_feat3_desc":"దీర్ఘకాలిక నేల ఆరోగ్యాన్ని కాపాడే నోట్స్.",
        "home_feat4_title":"బహు-భాష","home_feat4_desc":"ఆంగ్లం, హిందీ మరియు తెలుగు మద్దతు.",
        "home_feat5_title":"సమృద్ధ విశ్లేషణలు","home_feat5_desc":"ఇంటరాక్టివ్ చార్ట్‌లు: పంపిణీ, పోషకాలు, వర్షపాతం.",
        "home_feat6_title":"మోడల్ పారదర్శకత","home_feat6_desc":"కన్ఫ్యూజన్ మాట్రిక్స్, ఫీచర్ ప్రాముఖ్యత.",
        "home_stats_crops":"పంట రకాలు","home_stats_samples":"శిక్షణ నమూనాలు",
        "home_stats_accuracy":"మోడల్ ఖచ్చితత్వం","home_stats_langs":"భాషలు",
        "login_title":"తిరిగి స్వాగతం","login_subtitle":"డాష్‌బోర్డ్ యాక్సెస్ చేయడానికి సైన్ ఇన్ చేయండి",
        "login_username":"వినియోగదారు పేరు","login_password":"పాస్‌వర్డ్","login_btn":"సైన్ ఇన్ చేయండి",
        "login_no_account":"ఖాతా లేదా?","login_register":"ఇక్కడ నమోదు చేయండి",
        "login_error":"చెల్లని వినియోగదారు పేరు లేదా పాస్‌వర్డ్.","login_demo":"డెమో: admin / admin123",
        "pred_title":"పంట అంచనా","pred_subtitle":"ఉత్తమ పంట సిఫారసు పొందడానికి వ్యవసాయ వివరాలను నమోదు చేయండి.",
        "pred_soil":"నేల పోషకాలు","pred_climate":"వాతావరణ పరిస్థితులు","pred_rotation":"మునుపటి పంట",
        "label_N":"నత్రజని (N)","label_P":"భాస్వరం (P)","label_K":"పొటాషియం (K)",
        "label_temp":"ఉష్ణోగ్రత (°C)","label_humidity":"తేమ (%)","label_ph":"నేల pH",
        "label_rainfall":"వర్షపాతం (మిమీ)","label_prev":"మునుపటి పంట",
        "predict_btn":"పంట అంచనా వేయండి","reset_btn":"ఫారమ్ రీసెట్ చేయండి",
        "result_title":"సిఫారసు చేయబడిన పంట","result_confidence":"నమ్మకం",
        "result_fertilizer":"ఎరువుల సూచన","result_rotation":"మార్పిడి గమనిక","result_top5":"అగ్ర 5 సంభావ్యతలు",
        "dash_title":"విశ్లేషణ డాష్‌బోర్డ్","dash_subtitle":"2,200 పంట నమూనాల నుండి దృశ్య అంతర్దృష్టులు",
        "chart_dist":"పంట పంపిణీ","chart_nutrients":"సగటు నేల పోషకాలు",
        "chart_rainfall":"వర్షపాతం vs పంట","chart_ph":"నేల pH",
        "chart_corr":"ఫీచర్ సహసంబంధం","chart_prev":"మునుపటి పంట పౌనఃపున్యం",
        "perf_title":"మోడల్ పనితీరు","perf_subtitle":"రాండమ్ ఫారెస్ట్ — 1,760 నమూనాలపై శిక్షణ",
        "metric_accuracy":"ఖచ్చితత్వం","metric_precision":"ప్రెసిషన్","metric_recall":"రీకాల్","metric_f1":"F1 స్కోర్",
        "chart_confusion":"కన్ఫ్యూజన్ మాట్రిక్స్","chart_importance":"ఫీచర్ ప్రాముఖ్యత","perf_class_metrics":"తరగతి-వారీ మెట్రిక్స్",
        "footer_copy":"© 2025 స్మార్ట్ పంట సిఫారసు వ్యవస్థ. నిలకడైన వ్యవసాయం కోసం నిర్మించబడింది.",
    },
}

def get_text(lang: str, key: str) -> str:
    return TRANSLATIONS.get(lang, TRANSLATIONS["English"]).get(
        key, TRANSLATIONS["English"].get(key, key))

def available_languages() -> list:
    return list(TRANSLATIONS.keys())
